### ISSUE TITLE
logo-perseus

### ISSUE THREAD

**Issue by streaming10** [streaming10/Perseus-y-RC-Abogados#3]
![logo-perseus](https://user-images.githubusercontent.com/63341181/227750527-15db3929-7b1e-44a3-8779-7285686b1459.svg)

**Comment by streaming10** [comment]
<img src="https://user-images.githubusercontent.com/63341181/227750527-15db3929-7b1e-44a3-8779-7285686b1459.svg" alt="Logo de Perseus & RC Abogados" style="filter: grayscale(100%) brightness(400%) contrast(300%) sepia(100%) hue-rotate(-20deg) invert(100%) drop-shadow(0 0 0.1rem #821412)">

**Comment by rafacouto** [comment]
logo de página bien resuelto
